# Generated by Django 4.1.6 on 2023-11-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='PDF_archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='convenio_modificatorio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
