# Generated by Django 4.1.6 on 2023-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_convenio_pdf_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='tipo',
            field=models.CharField(choices=[('DIV', 'Diversas Instituciones'), (
                'INTER', 'Internacionales'), ('NAC', 'Nacionales'), ('VARIOS', 'Varios')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CategoriaConvenio',
        ),
    ]
