# Generated by Django 4.1.6 on 2023-12-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0003_alter_convenio_tipo_delete_categoriaconvenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='tipo',
            field=models.CharField(choices=[('Diversas Instituciones', 'Diversas Instituciones'), (
                'Internacionales', 'Internacionales'), ('Nacionales', 'Nacionales'), ('Varios', 'Varios')], max_length=50),
        ),
    ]
