# Generated by Django 4.1.6 on 2023-12-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0004_alter_convenio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='convenio',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='ConvenioParticipantes',
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
    ]
