# Generated by Django 4.1.6 on 2023-12-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0007_alter_convenio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='PDF_archivo',
            field=models.FileField(blank=True, null=True,
                                   upload_to='convenios'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='convenio_modificatorio',
            field=models.FileField(blank=True, null=True,
                                   upload_to='convenios_modificatorios'),
        ),
    ]
