# Generated by Django 4.1.6 on 2023-12-03 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0009_alter_convenio_pdf_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='PDF_archivo',
            field=models.FileField(blank=True, null=True, upload_to='convenios', validators=[
                                   django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='convenio_modificatorio',
            field=models.FileField(blank=True, null=True, upload_to='convenios_modificatorios', validators=[
                                   django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
