# Generated by Django 4.2.2 on 2023-12-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0010_alter_convenio_pdf_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='PDF_estado',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='PNT',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='documento_editable',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='estado',
            field=models.CharField(blank=True, choices=[('TERMINADO', 'Terminado'), ('ESPERA', 'En espera'), (
                'NO EMPEZADO', 'No empezado')], default='ESPERA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='firmado',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='recurso_economico',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='visto_bueno',
            field=models.CharField(blank=True, choices=[(
                'SI', 'Sí'), ('NO', 'No')], default='NO', max_length=10, null=True),
        ),
    ]
